# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'DailyKorean' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DailyKorean
  pod 'WKWebViewJavascriptBridge', '~> 1.2.0'  
  pod 'SnapKit', '~> 5.0.0'

  target 'DailyKoreanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DailyKoreanUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
